defaults: &defaults
  adapter: "sqlite"

development:
  database: db/brew_book_development.db
  <<: *defaults
  
  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  postgres
  #     database: sample_development
  #     username: the_user
  #     password: secrets
  #     host:     localhost
  #   repo2:
  #     ...
      
test: &test
  database: ":memory:"
  <<: *defaults

production:
  database: db/brew_book_production.db
  <<: *defaults

cucumber:
  <<: *test
