<%
require 'cgi'
require 'uri'

begin
  uri = URI.parse(ENV["DATABASE_URL"] || "http://google.com")
rescue URI::InvalidURIError
  raise "Invalid DATABASE_URL"
end

def attribute(name, value)
  value ? "#{name}: #{value}" : ""
end

adapter = uri.scheme
adapter = "postgresql" if adapter == "postgres"

database = (uri.path || "").split("/")[1]

username = uri.user
password = uri.password

host = uri.host
port = uri.port

params = CGI.parse(uri.query || "")
%>

defaults: &defaults
  adapter: "sqlite"

development:
  database: db/brew_book_development.db
  <<: *defaults
  
  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  postgres
  #     database: sample_development
  #     username: the_user
  #     password: secrets
  #     host:     localhost
  #   repo2:
  #     ...
      
test: &test
  database: ":memory:"
  <<: *defaults

production:
  <%= attribute "adapter", adapter %>
  <%= attribute "database", database %>
  <%= attribute "username", username %>
  <%= attribute "password", password %>
  <%= attribute "host", host %>
  <%= attribute "port", port %>

cucumber:
  <<: *test
